# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lg2015_gibbs_iter_lg2015 <- function(n, z, R, Rz, a, b) {
    .Call(`_sampletmvn_lg2015_gibbs_iter_lg2015`, n, z, R, Rz, a, b)
}

lg2015_gibbs_iter_be2017 <- function(n, z, R, Rz, a, b) {
    .Call(`_sampletmvn_lg2015_gibbs_iter_be2017`, n, z, R, Rz, a, b)
}

hamiltonian_zigzag <- function(n, Prec, A, lb, ub, init, p_init, T) {
    .Call(`_sampletmvn_hamiltonian_zigzag`, n, Prec, A, lb, ub, init, p_init, T)
}

rsm <- function(n_samples, mode, Sigma, Prec_mode, lb, ub, A) {
    .Call(`_sampletmvn_rsm`, n_samples, mode, Sigma, Prec_mode, lb, ub, A)
}

ry2004_gibbs_iter_lg2015 <- function(n, alpha, z, D, Dz, lb, ub) {
    .Call(`_sampletmvn_ry2004_gibbs_iter_lg2015`, n, alpha, z, D, Dz, lb, ub)
}

ry2004_gibbs_iter_be2017 <- function(n, alpha, z, D, Dz, lb, ub) {
    .Call(`_sampletmvn_ry2004_gibbs_iter_be2017`, n, alpha, z, D, Dz, lb, ub)
}

rtuvn <- function(n, mean, sd, lower, upper) {
    .Call(`_sampletmvn_rtuvn`, n, mean, sd, lower, upper)
}

