# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hamiltonian_zigzag <- function(n, Prec, A, lb, ub, init, p_init, T) {
    .Call(`_sampletmvn_hamiltonian_zigzag`, n, Prec, A, lb, ub, init, p_init, T)
}

lg2015 <- function(n, z, R, Rz, a, b, sampler) {
    .Call(`_sampletmvn_lg2015`, n, z, R, Rz, a, b, sampler)
}

#' @param R upper cholesky factor of precision
#' @param lb lower bound with mean subtracted
#' @param ub upper bound with mean subtracted
rhmc <- function(n, R, lb, ub, burnin, initial, traj_length, max_stepsize, max_relative_stepsize, implicit_iter) {
    .Call(`_sampletmvn_rhmc`, n, R, lb, ub, burnin, initial, traj_length, max_stepsize, max_relative_stepsize, implicit_iter)
}

rsm <- function(n_samples, mode, Sigma, Prec_mode, lb, ub, A) {
    .Call(`_sampletmvn_rsm`, n_samples, mode, Sigma, Prec_mode, lb, ub, A)
}

rsm_axis <- function(n_samples, mode, Sigma, Prec_mode, lb, ub) {
    .Call(`_sampletmvn_rsm_axis`, n_samples, mode, Sigma, Prec_mode, lb, ub)
}

ry2004 <- function(n, alpha, z, D, Dz, lb, ub, sampler) {
    .Call(`_sampletmvn_ry2004`, n, alpha, z, D, Dz, lb, ub, sampler)
}

rtuvn <- function(n, mean, sd, lower, upper) {
    .Call(`_sampletmvn_rtuvn`, n, mean, sd, lower, upper)
}

