# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtuvn <- function(n, mean, sd, lower, upper) {
    .Call(`_sampletmvn_rtuvn`, n, mean, sd, lower, upper)
}

gibbs_mixed_rejection <- function(n, z, R, Rz, a, b) {
    .Call(`_sampletmvn_gibbs_mixed_rejection`, n, z, R, Rz, a, b)
}

rcpparma_hello_world <- function() {
    .Call(`_sampletmvn_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_sampletmvn_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_sampletmvn_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_sampletmvn_rcpparma_bothproducts`, x)
}

rsm <- function(n_samples, mode, Sigma, Prec_mode, lb, ub, A) {
    .Call(`_sampletmvn_rsm`, n_samples, mode, Sigma, Prec_mode, lb, ub, A)
}

